#!/usr/bin/env bash

tmp_dir=./tmp_ds_data
base_download_url="https://github.com/WickedElm/feature_residuals_with_pretraining/releases/download/v1.0.0"

# Create data directory if needed
if [ ! -d ${tmp_dir} ];
then
    mkdir ${tmp_dir}
    chmod 755 ${tmp_dir}
fi

echo "Downloading data."

###
# Base datasets files.
###
wget -q ${base_download_url}/datasets.aa
wget -q ${base_download_url}/datasets.ab
wget -q ${base_download_url}/datasets.ac
wget -q ${base_download_url}/datasets.ad
wget -q ${base_download_url}/datasets.ae
wget -q ${base_download_url}/datasets.af
wget -q ${base_download_url}/datasets.ag
cat datasets.aa datasets.ab datasets.ac datasets.ad datasets.ae datasets.af datasets.ag > datasets.tar.gz
tar xfz datasets.tar.gz
rm -f datasets.tar.gz datasets.aa datasets.ab datasets.ac datasets.ad datasets.ae datasets.af datasets.ag

###
# NF-UNSW-NB15-V2
###
training_file=conference_nf-unsw-nb15-v2_ae_tuning_train.pkl
validation_file=conference_nf-unsw-nb15-v2_ae_tuning_validation.pkl
test_file=conference_nf-unsw-nb15-v2_ae_tuning_test.pkl

wget -q ${base_download_url}/${training_file} -O ${tmp_dir}/${training_file}
wget -q ${base_download_url}/${test_file} -O ${tmp_dir}/${test_file}
wget -q ${base_download_url}/${validation_file} -O ${tmp_dir}/${validation_file}

###
# NF-BOT-IOT-V2
###
training_file=conference_nf-bot-iot-v2_ae_tuning_train.pkl
validation_file=conference_nf-bot-iot-v2_ae_tuning_validation.pkl
test_file=conference_nf-bot-iot-v2_ae_tuning_test.pkl

wget -q ${base_download_url}/${training_file} -O ${tmp_dir}/${training_file}
wget -q ${base_download_url}/${test_file} -O ${tmp_dir}/${test_file}
wget -q ${base_download_url}/${validation_file} -O ${tmp_dir}/${validation_file}

###
# NF-CSE-CIC-IDS2018-V2
###
training_file=conference_nf-cse-cic-ids2018-v2_ae_tuning_train.pkl
validation_file=conference_nf-cse-cic-ids2018-v2_ae_tuning_validation.pkl
test_file=conference_nf-cse-cic-ids2018-v2_ae_tuning_test.pkl

wget -q ${base_download_url}/${training_file} -O ${tmp_dir}/${training_file}
wget -q ${base_download_url}/${test_file} -O ${tmp_dir}/${test_file}
wget -q ${base_download_url}/${validation_file} -O ${tmp_dir}/${validation_file}

###
# NF-TON-IOT-V2
###
training_file=conference_nf-ton-iot-v2_ae_tuning_train.pkl
validation_file=conference_nf-ton-iot-v2_ae_tuning_validation.pkl
test_file=conference_nf-ton-iot-v2_ae_tuning_test.pkl

wget -q ${base_download_url}/${training_file} -O ${tmp_dir}/${training_file}
wget -q ${base_download_url}/${test_file} -O ${tmp_dir}/${test_file}
wget -q ${base_download_url}/${validation_file} -O ${tmp_dir}/${validation_file}

###
# NF-UNSW_NB15-V2 SPARSE
###
training_file=conference_sf_nf_unsw_nb15_v2_ae_tuning_train.pkl
validation_file=conference_sf_nf_unsw_nb15_v2_ae_tuning_validation.pkl
test_file=conference_sf_nf_unsw_nb15_v2_ae_tuning_test.pkl

wget -q ${base_download_url}/${training_file} -O ${tmp_dir}/${training_file}
wget -q ${base_download_url}/${test_file} -O ${tmp_dir}/${test_file}
wget -q ${base_download_url}/${validation_file} -O ${tmp_dir}/${validation_file}

###
# NF-BOT-IOT-V2 SPARSE
###
training_file=conference_sf_nf_bot_iot_v2_ae_tuning_train.pkl
validation_file=conference_sf_nf_bot_iot_v2_ae_tuning_validation.pkl
test_file=conference_sf_nf_bot_iot_v2_ae_tuning_test.pkl

wget -q ${base_download_url}/${training_file} -O ${tmp_dir}/${training_file}
wget -q ${base_download_url}/${test_file} -O ${tmp_dir}/${test_file}
wget -q ${base_download_url}/${validation_file} -O ${tmp_dir}/${validation_file}

###
# NF-CSE-CIC-IDS2018-V2 SPARSE
###
training_file=conference_sf_nf_cse_cic_ids2018_v2_ae_tuning_train.pkl
validation_file=conference_sf_nf_cse_cic_ids2018_v2_ae_tuning_validation.pkl
test_file=conference_sf_nf_cse_cic_ids2018_v2_ae_tuning_test.pkl

wget -q ${base_download_url}/${training_file} -O ${tmp_dir}/${training_file}
wget -q ${base_download_url}/${test_file} -O ${tmp_dir}/${test_file}
wget -q ${base_download_url}/${validation_file} -O ${tmp_dir}/${validation_file}

###
# NF-TON-IOT-V2 SPARSE
###
training_file=conference_sf_nf_ton_iot_v2_ae_tuning_train.pkl
validation_file=conference_sf_nf_ton_iot_v2_ae_tuning_validation.pkl
test_file=conference_sf_nf_ton_iot_v2_ae_tuning_test.pkl

wget -q ${base_download_url}/${training_file} -O ${tmp_dir}/${training_file}
wget -q ${base_download_url}/${test_file} -O ${tmp_dir}/${test_file}
wget -q ${base_download_url}/${validation_file} -O ${tmp_dir}/${validation_file}

echo "Downloading complete."
